#include<iostream>
#include<cmath>
#include<string>
#include<cstring>
#include<climits>
#include<cstdlib>
#include<algorithm>
#include<vector>
#include<set>
#include<map>
#include<unordered_map>
#include<stack>
#include<deque>
//13 headers why?
using namespace std;
// Autogenerated, do not edit below this line
#define ll long long
#define ck cout<<"check\n"
#define wis(x) cerr << #x << " is " << x << endl
#define MOD 1000000007
#define mx(a,b) ( (a) > (b) ? (a) : (b))
#define mn(a,b) ( (a) < (b) ? (a) : (b))
#define test int t;cin>>t;while(t--)
#define f(i,L,R) for (int i = L; i < R; i++)
#define fe(i,L,R) for (int i = L; i <= R; i++)
#define ff(i,L,R) for (int i = L; i > R; i--)
#define ffe(i,L,R) for (int i = L; i >= R; i--)
#define mp(a,b) make_pair(a,b)
#define ain(a,i,n) f(j,i,n) cin>>a[j]
#define aout(a,i,n) f(j,i,n) cout<<a[j]<<" \n"[j==n-1]
#define cnl cout<<endl
typedef vector<int> vi;
typedef vector<ll> vll;
typedef vector<vi> vvi;
typedef vector<pair<int,int> > vii;
#define fi first
#define se second
#define pb push_back
#define all(c) (c).begin(),(c).end()
#define take freopen("inp.txt","r",stdin)
// Autogenerated, do not edit above this line
int main()
{
	ios::sync_with_stdio(false);
	#ifndef ONLINE_JUDGE
	take;
	#endif
	test
	{
		int n,m;
		cin>>n>>m;
		vi v(n+1,0);
	//	vii in;
		f(i,0,m)
		{
			int ui,vi;
			cin>>ui>>vi;
			v[ui]++;v[vi]++;
		}
	//	aout(v,1,n+1);
		sort(all(v));
	//	aout(v,1,n+1);
		vi ans(n+1,0);
		fe(i,1,n) ans[v[i]]++;
		fe(i,1,n) ans[i]+=ans[i-1];
		fe(i,1,n) ans[i]=mn(ans[i],n-1);
		aout(ans,0,n);
	}
	return 0;
}